### ISSUE TITLE
allow_sed_supersat misnamed?

### ISSUE THREAD

**Issue by andrewgettelman** [ESCOMP/PUMAS#10]
Greetings,

The 'allow_sed_supersat' flag is misnamed, and should probably be the opposite of it's name.

In the MG3 code near the end: 

           if (qtmp > qvn .and. qvn > 0 .and. allow_sed_supersat) then

(supersaturation removed)

           end if

So it should probably be 'remove_residual_supersat'

If it is true, then supersaturation is removed, which is not the intent: it's the opposite.  Renaming would be easiest, and flipping the logical of the default for CAM6

**Comment by Katetc** [comment]
Check the current default value for namelist and we want to not change whether it's going into the loop. Change the name not the value.

**Comment by andrewgettelman** [comment]
This is done (at least in the CAM code, not sure why not on PUMAS master)...now called remove_supersat.
