### ISSUE TITLE
MG3 not working with CAM5 physics and FV3

### ISSUE THREAD

**Issue by Katetc** [ESCOMP/PUMAS#12]
I made up this test out of thin air:
ERP_D_Ln9.C48_C48_mg17.QPC5.cheyenne_intel.cam-outfrq9s_mg3

And it crashed before the first time step with the error:
57:forrtl: severe (408): fort: (2): Subscript #4 of the array Q has value 4 which is greater than the upper bound of 3
57:
57:Image              PC                Routine            Line        Source
57:cesm.exe           00000000086470A6  Unknown               Unknown  Unknown
57:cesm.exe           0000000004FE4334  fv_mapz_mod_mp_mo        3371  fv_mapz.F90
57:cesm.exe           0000000004AFFCD6  fv_dynamics_mod_m         430  fv_dynamics.F90
57:libiomp5.so        00002B862B4C5D43  __kmp_invoke_micr     Unknown  Unknown
57:libiomp5.so        00002B862B455D65  __kmp_fork_call       Unknown  Unknown
57:libiomp5.so        00002B862B415C60  __kmpc_fork_call      Unknown  Unknown
57:cesm.exe           0000000004ADEF3C  fv_dynamics_mod_m         425  fv_dynamics.F90

While we have a handful of tests of MG3 in CAM, I believe most of them use the fv or se dycore and CAM6 physics. It looks like there is a problem with tracers in fv3 and the added species in MG3, perhaps. I don't think this is because of recent changes on our part, but it will take some time to look into.

**Comment by andrewgettelman** [comment]
Kate, this is not worth pursuing right now. We don't intend to run with FV3: it is likely an issue for FV3 and I don't want you or anyone else spending time on it right now.

**Comment by Katetc** [comment]
That's fine. I just wanted to document it as a known issue in case somebody else runs across it.

**Comment by andrewgettelman** [comment]
Closing. No action taken.
