### ISSUE TITLE
Potential typo in micro_mg3_0.F90

### ISSUE THREAD

**Issue by sjsprecious** [ESCOMP/PUMAS#32]
While I am refactoring the revised PUMAS code for GPU porting, I find the following line of code very suspicious:

https://github.com/ESCOMP/PUMAS/blob/release/cam/micro_mg3_0.F90#L3068

Should it be "ums **(i,k)** = ums **(i,k)** * micro_mg_vtrmi_factor" rather than ums **(:,k)** = ums **(:,k)** * micro_mg_vtrmi_factor?

If so, I could fix it in my coming PR. If not, I will leave it as the current form.

**Comment by andrewgettelman** [comment]
Hi @sjsprecious,

Thanks for finding this. I think it is a mistake. Probably when this was converted to a loop over i that was not changed. If I read it correctly it should't change answers, but yes, go ahead and make the change in your PR if you would.

Thanks for catching that!

Regards,

Andrew

**Comment by sjsprecious** [comment]
Thanks @andrewgettelman . Will do it in my coming PR.

**Comment by sjsprecious** [comment]
Fix in https://github.com/ESCOMP/PUMAS/pull/34.
