### ISSUE TITLE
Broken GPU code after merging the ML code

### ISSUE THREAD

**Issue by sjsprecious** [ESCOMP/PUMAS#55]
After looking through the latest tag `pumas_cam-release_v1.30`, I think the PUMAS GPU code is broken now since many new variables / subroutines are not GPU-enabled.

Also some subroutines are not implemented efficiently as we expect to push both `mgncol` and `nlev` loops into each subroutine.

Need a corresponding CAM code to test and verify my statement here.

**Comment by Katetc** [comment]
Addressed in pumas_cam-release_v1.36 and coming into CAM with -[ESCOMP/CAM PR # 702 ](https://github.com/ESCOMP/CAM/pull/702)
