### ISSUE TITLE
Wrong variable name in the OpenACC GPU directives

### ISSUE THREAD

**Issue by sjsprecious** [ESCOMP/PUMAS#67]
In the latest PUMAS tag, the variable `proc_rates%nr_out` no longer exists. Thus it should be removed from this line https://github.com/ESCOMP/PUMAS/blob/release/cam/micro_pumas_v1.F90#L1199. Otherwise, the GPU compilation will fail.

**Comment by Katetc** [comment]
Addressed in pumas_cam-release_v1.36 and coming into CAM with -[ESCOMP/CAM PR # 702 ](https://github.com/ESCOMP/CAM/pull/702)
